class Recipe{
  String label;
  String imageUrl;

  int servings;
  List<Ingredient> ingredients;

  Recipe(this.label, this.imageUrl,this.servings, this.ingredients);

  static List<Recipe> samples = [
    Recipe(
      'Rawon',
      'assets/rawon.jpg',
      4,
      [
        Ingredient(500, 'gram', 'daging sapi'),
        Ingredient(2, 'batang', 'serai, memarkan'),
        Ingredient(3, 'lembar', 'daun salam'),
        Ingredient(3, 'lembar', 'daun jeruk'),
        Ingredient(2, 'sendok teh', 'garam'),
        Ingredient(1, 'sendok teh', 'gula pasir'),
        Ingredient(200, 'gram', 'kacang kedelai hitam'),
        Ingredient(3, 'sendok makan', 'minyak goreng'),
        Ingredient(5, 'buah', 'cabe rawit merah, iris halus'),
        Ingredient(3, 'buah', 'tomat, belah 4'),
        Ingredient(2, 'buah', 'jeruk limo, ambil airnya'),
        Ingredient(1, 'batang', 'sereh, iris halus'),
        Ingredient(2, 'cm', 'kunyit, bakar'),
        Ingredient(1, 'cm', 'jahe, bakar'),
        Ingredient(1, 'buah', 'bawang putih, bakar'),
        Ingredient(1, 'buah', 'bawang merah, bakar'),
        Ingredient(1, 'sendok teh', 'ketumbar, sangrai'),
        Ingredient(1, 'sendok teh', 'merica butiran, sangrai'),
        Ingredient(3, 'buah', 'bawang merah, iris halus, goreng'),
        Ingredient(3, 'buah', 'bawang putih, iris halus, goreng')
      ],
    ),
    Recipe(
      'Rujak Cingur',
      'assets/rujakcingur.jpg',
      2,
      [
        Ingredient(250, 'gram', 'cingur, rebus, potong tipis'),
        Ingredient(200, 'gram', 'tahu, goreng, potong-potong'),
        Ingredient(150, 'gram', 'tempe, goreng, potong-potong'),
        Ingredient(200, 'gram', 'kol, iris halus, rebus sebentar'),
        Ingredient(200, 'gram', 'tauge, rebus sebentar'),
        Ingredient(2, 'buah', 'timun, potong dadu'),
        Ingredient(2, 'buah', 'kedondong, potong dadu'),
        Ingredient(100, 'gram', 'kacang tanah, sangrai'),
        Ingredient(3, 'buah', 'cabe rawit merah, haluskan'),
        Ingredient(2, 'buah', 'cabe rawit hijau, haluskan'),
        Ingredient(2, 'sendok makan', 'gula merah, sisir'),
        Ingredient(3, 'sendok makan', 'air asam jawa'),
        Ingredient(1, 'sendok teh', 'garam'),
        Ingredient(2, 'sendok makan', 'petis udang'),
        Ingredient(2, 'sendok makan', 'minyak goreng, untuk menumis'),
        Ingredient(2, 'lembar', 'daun jeruk'),
        Ingredient(2, 'lembar', 'daun salam'),
        Ingredient(1, 'batang', 'serai, memarkan'),
        Ingredient(2, 'cm', 'kunyit, bakar, haluskan'),
        Ingredient(5, 'butir', 'bawang merah'),
        Ingredient(3, 'siung', 'bawang putih'),
        Ingredient(2, 'buah', 'tomat, belah 4')
      ],
    ),
    // Tambahkan resep-resep makanan Jawa Timur lainnya di sini
    Recipe(
      'Soto Ayam',
      'assets/sotoayam.jpg',
      4,
      [
        Ingredient(1, 'ekor', 'ayam kampung'),
        Ingredient(2, 'liter', 'air'),
        Ingredient(2, 'batang', 'serai, memarkan'),
        Ingredient(5, 'lembar', 'daun jeruk'),
        Ingredient(2, 'lembar', 'daun salam'),
        Ingredient(2, 'cm', 'jahe, memarkan'),
        Ingredient(3, 'siung', 'bawang putih, memarkan'),
        Ingredient(5, 'buah', 'bawang merah, memarkan'),
        Ingredient(1, 'sendok teh', 'merica butiran, sangrai'),
        Ingredient(3, 'buah', 'jeruk nipis, ambil airnya'),
        Ingredient(2, 'sendok makan', 'minyak goreng'),
        Ingredient(2, 'sendok teh', 'garam'),
        Ingredient(1, 'sendok teh', 'gula pasir'),
        Ingredient(250, 'gram', 'soun, seduh, tiriskan'),
        Ingredient(2, 'buah', 'tomat, potong-potong'),
        Ingredient(2, 'sendok makan', 'bawang merah goreng'),
        Ingredient(2, 'sendok makan', 'daun bawang, iris halus'),
        Ingredient(2, 'sendok makan', 'seledri, iris halus'),
        Ingredient(2, 'buah', 'telur, rebus, belah dua')
      ],
    ),
    // Tambahkan resep-resep makanan Jawa Timur lainnya di sini
    Recipe(
      'Lontong Balap',
      'assets/lontongbalap.jpg',
      4,
      [
        Ingredient(250, 'gram', 'tauge, rebus sebentar'),
        Ingredient(200, 'gram', 'lontong, potong-potong'),
        Ingredient(100, 'gram', 'tahu, potong-potong, goreng'),
        Ingredient(100, 'gram', 'lentho, goreng'),
        Ingredient(100, 'gram', 'emping'),
        Ingredient(2, 'sendok makan', 'bawang merah goreng'),
        Ingredient(2, 'sendok makan', 'kecap manis'),
        Ingredient(1, 'sendok teh', 'air jeruk limo'),
        Ingredient(1, 'sendok teh', 'garam'),
        Ingredient(1/2, 'sendok teh', 'gula pasir'),
        Ingredient(1/2, 'sendok teh', 'kaldu ayam bubuk'),
        Ingredient(1/4, 'sendok teh', 'merica bubuk'),
        Ingredient(1/4, 'sendok teh', 'bubuk cabe rawit'),
        Ingredient(1/4, 'sendok teh', 'bawang putih goreng, haluskan'),
      ],
    ),
    Recipe(
      'Lontong Kupang',
      'assets/lontongkupang.jpg',
      4,
      [
        Ingredient(300, 'gram', 'kupang, cuci bersih'),
        Ingredient(200, 'gram', 'lontong, potong-potong'),
        Ingredient(100, 'gram', 'tauge, rebus sebentar'),
        Ingredient(100, 'gram', 'kentang, rebus, potong-potong'),
        Ingredient(50, 'gram', 'bawang merah, iris halus, goreng'),
        Ingredient(2, 'batang', 'daun bawang, iris halus'),
        Ingredient(2, 'sendok makan', 'kecap manis'),
        Ingredient(2, 'sendok makan', 'minyak goreng'),
        Ingredient(1, 'sendok teh', 'garam'),
        Ingredient(1/2, 'sendok teh', 'kaldu ayam bubuk'),
        Ingredient(1/2, 'sendok teh', 'merica bubuk'),
        Ingredient(1/4, 'sendok teh', 'gula pasir'),
        Ingredient(1/4, 'sendok teh', 'bubuk cabe rawit'),
      ],
    ),
    Recipe(
      'Nasi Pecel',
      'assets/nasipecel.jpg',
      2,
      [
        Ingredient(200, 'gram', 'nasi putih, hangatkan'),
        Ingredient(100, 'gram', 'kacang panjang, rebus, potong-potong'),
        Ingredient(100, 'gram', 'tauge, rebus sebentar'),
        Ingredient(100, 'gram', 'kol, rebus, iris halus'),
        Ingredient(100, 'gram', 'kentang, rebus, potong-potong'),
        Ingredient(50, 'gram', 'lontong, potong-potong'),
        Ingredient(2, 'buah', 'tomat, iris'),
        Ingredient(2, 'sendok makan', 'bawang merah goreng'),
        Ingredient(2, 'sendok makan', 'sambal pecel'),
        Ingredient(2, 'sendok makan', 'petis udang'),
        Ingredient(2, 'sendok makan', 'kecap manis'),
        Ingredient(1, 'sendok teh', 'gula pasir'),
        Ingredient(1, 'sendok teh', 'garam'),
      ],
    ),
    Recipe(
      'Lontong Sayur Madura',
      'assets/lontongsayurmadura.jpg',
      4,
      [
        Ingredient(300, 'gram', 'lontong, potong-potong'),
        Ingredient(200, 'gram', 'sayur kangkung'),
        Ingredient(100, 'gram', 'tauge, rebus sebentar'),
        Ingredient(100, 'gram', 'kulit tahu, potong kotak, goreng'),
        Ingredient(100, 'gram', 'babat sapi, rebus, potong kotak'),
        Ingredient(100, 'gram', 'daging sapi, rebus, potong kotak'),
        Ingredient(50, 'gram', 'soun, seduh, tiriskan'),
        Ingredient(2, 'lembar', 'daun salam'),
        Ingredient(2, 'lembar', 'daun jeruk'),
        Ingredient(2, 'lembar', 'daun bawang, iris halus'),
        Ingredient(2, 'sendok makan', 'bawang merah goreng'),
        Ingredient(2, 'sendok makan', 'minyak goreng'),
        Ingredient(2, 'sendok makan', 'bumbu kacang'),
        Ingredient(1, 'sendok teh', 'garam'),
        Ingredient(1, 'sendok teh', 'gula pasir'),
        Ingredient(1/2, 'sendok teh', 'kaldu ayam bubuk'),
        Ingredient(1/2, 'sendok teh', 'merica bubuk'),
        Ingredient(1/4, 'sendok teh', 'bubuk cabe rawit'),
        Ingredient(1/4, 'sendok teh', 'air asam jawa'),
      ],
    ),
    Recipe(
      'Tahu Campur',
      'assets/tahucampur.jpg',
      4,
      [
        Ingredient(4, 'buah', 'tahu putih, potong-potong, goreng'),
        Ingredient(100, 'gram', 'tauge, rebus sebentar'),
        Ingredient(100, 'gram', 'kulit tahu, potong kotak, goreng'),
        Ingredient(100, 'gram', 'kol, iris halus, rebus sebentar'),
        Ingredient(100, 'gram', 'babat sapi, rebus, potong kotak'),
        Ingredient(100, 'gram', 'daging sapi, rebus, potong kotak'),
        Ingredient(50, 'gram', 'soun, seduh, tiriskan'),
        Ingredient(2, 'lembar', 'daun salam'),
        Ingredient(2, 'lembar', 'daun jeruk'),
        Ingredient(2, 'lembar', 'daun bawang, iris halus'),
        Ingredient(2, 'sendok makan', 'bawang merah goreng'),
        Ingredient(2, 'sendok makan', 'minyak goreng'),
        Ingredient(2, 'sendok makan', 'bumbu kacang'),
        Ingredient(1, 'sendok teh', 'garam'),
        Ingredient(1, 'sendok teh', 'gula pasir'),
        Ingredient(1/2, 'sendok teh', 'kaldu ayam bubuk'),
        Ingredient(1/2, 'sendok teh', 'merica bubuk'),
        Ingredient(1/4, 'sendok teh', 'bubuk cabe rawit'),
        Ingredient(1/4, 'sendok teh', 'air asam jawa'),
      ],
    ),
    Recipe(
      'Sate Madura',
      'assets/satemadura.jpg',
      4,
      [
        Ingredient(500, 'gram', 'daging sapi, potong dadu'),
        Ingredient(200, 'gram', 'lemak daging sapi, potong dadu'),
        Ingredient(1, 'batang', 'serai, memarkan'),
        Ingredient(5, 'lembar', 'daun jeruk'),
        Ingredient(2, 'lembar', 'daun salam'),
        Ingredient(2, 'cm', 'jahe, memarkan'),
        Ingredient(5, 'butir', 'bawang merah, haluskan'),
        Ingredient(3, 'siung', 'bawang putih, haluskan'),
        Ingredient(2, 'sendok makan', 'kecap manis'),
        Ingredient(2, 'sendok makan', 'minyak goreng'),
        Ingredient(1, 'sendok teh', 'garam'),
        Ingredient(1/2, 'sendok teh', 'kaldu ayam bubuk'),
        Ingredient(1/2, 'sendok teh', 'merica bubuk'),
        Ingredient(1/4, 'sendok teh', 'gula pasir'),
        Ingredient(1/4, 'sendok teh', 'bubuk cabe rawit'),
        Ingredient(1/4, 'sendok teh', 'air asam jawa'),
      ],
    ),
    Recipe(
      'Soto Lamongan',
      'assets/sotolamongan.jpg',
      4,
      [
        Ingredient(1, 'ekor', 'ayam kampung'),
        Ingredient(2, 'liter', 'air'),
        Ingredient(2, 'batang', 'serai, memarkan'),
        Ingredient(5, 'lembar', 'daun jeruk'),
        Ingredient(2, 'lembar', 'daun salam'),
        Ingredient(2, 'cm', 'jahe, memarkan'),
        Ingredient(3, 'siung', 'bawang putih, haluskan'),
        Ingredient(5, 'buah', 'bawang merah, haluskan'),
        Ingredient(1, 'sendok teh', 'merica butiran, sangrai'),
        Ingredient(3, 'buah', 'jeruk nipis, ambil airnya'),
        Ingredient(2, 'sendok makan', 'minyak goreng'),
        Ingredient(2, 'sendok makan', 'bawang merah goreng, untuk taburan'),
        Ingredient(2, 'sendok makan', 'daun bawang, iris halus'),
        Ingredient(2, 'sendok makan', 'seledri, iris halus'),
        Ingredient(2, 'buah', 'telur, rebus, belah dua'),
        Ingredient(200, 'gram', 'tauge, seduh air panas, tiriskan'),
        Ingredient(2, 'batang', 'sereh, memarkan'),
        Ingredient(2, 'sendok makan', 'bawang goreng, untuk taburan'),
        Ingredient(2, 'sendok makan', 'sambal'),
        Ingredient(1, 'sendok teh', 'gula pasir'),
        Ingredient(1, 'sendok teh', 'garam'),
      ],
    ),
  ];

}

class Ingredient{
  double quantity;
  String measure;
  String name;

  Ingredient(this.quantity, this.measure, this.name);
}